backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "vystavy"
    label: "Výstavy"
    label_singular: "výstava"
    folder: "src/vystavy"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - name: "layout"
        label: "layout"
        widget: "hidden"
        default: "vystava.html"
      - name: "title"
        label: "Název výstavy"
        widget: "string"
      - name: "mesto"
        label: "Město"
        widget: "string"
      - name: "datum_od"
        label: "datum od"
        widget: "date"
      - name: "datum_do"
        label: "datum do"
        widget: "date"
      - name: "upoutavka"
        label: "Upoutávka"
        widget: "string"
      - name: "upoutavka_obrazek"
        label: "Upoutávka - obrázek (url)"
        widget: "string"
        required: false
      - name: "oteviraci_doba"
        label: "otevírací doba"
        widget: "hidden"
        default: ""
      - name: "plakatek"
        label: "plakátek (url)"
        widget: "string"
        required: false
      - name: "fotogalerie"
        label: "fotogalerie"
        widget: "hidden"
        default: ""
      - name: "ohlasy"
        label: "ohlasy"
        widget: "hidden"
        default: ""
      - name: "pro_media"
        label: "pro media"
        widget: "hidden"
        default: ""
      - name: "body"
        label: "Hlavní text o výstavě"
        widget: "markdown"
  - name: "pages"
    label: "stránky"
    files:
      - file: "src/about.md"
        name: "o_nas"
        label: "O nás"
        delete: false
        fields:
          - label: "Skupiny"
            name: "collection"
            widget: "string"
          - label: "Pozice v menu"
            name: "menuposition"
            widget: "number"
            required: false
            valueType: "int"
            min: 0
            default: 999
          - name: "body"
            label: "Hlavní text stránky"
            widget: "markdown"
      - file: "src/faq.md"
        name: "faq"
        label: "Časté otázky"
        delete: false
        fields:
          - label: "Skupiny"
            name: "collection"
            widget: "string"
          - label: "Pozice v menu"
            name: "menuposition"
            widget: "number"
            required: false
            valueType: "int"
            min: 0
            default: 999
          - name: "body"
            label: "Hlavní text stránky"
            widget: "markdown"
      - file: "src/historie.md"
        name: "historie"
        label: "Historie kostky.org"
        delete: false
        fields:
          - label: "Skupiny"
            name: "collection"
            widget: "string"
          - label: "Pozice v menu"
            name: "menuposition"
            widget: "number"
            required: false
            valueType: "int"
            min: 0
            default: 999
          - name: "body"
            label: "Hlavní text stránky"
            widget: "markdown"
      - file: "src/MOC.md"
        name: "MOC"
        label: "Naše modely"
        delete: false
        fields:
          - label: "Skupiny"
            name: "collection"
            widget: "string"
          - label: "Pozice v menu"
            name: "menuposition"
            widget: "number"
            required: false
            valueType: "int"
            min: 0
            default: 999
          - name: "body"
            label: "Hlavní text stránky"
            widget: "markdown"
      - file: "src/vystavy.md"
        name: "vystavy"
        label: "Naše výstavy"
        delete: false
        fields:
          - label: "Skupiny"
            name: "collection"
            widget: "string"
          - label: "Pozice v menu"
            name: "menuposition"
            widget: "number"
            required: false
            valueType: "int"
            min: 0
            default: 999
          - name: "body"
            label: "Hlavní text stránky"
            widget: "markdown"
      - file: "src/index.md"
        name: "home"
        label: "Domovská stránka"
        delete: false
        fields:
          - label: "Skupiny"
            name: "collection"
            widget: "string"
          - label: "Pozice v menu"
            name: "menuposition"
            widget: "number"
            required: false
            valueType: "int"
            min: 0
            default: 999
          - name: "body"
            label: "Hlavní text stránky"
            widget: "markdown"
